config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'menus#index'
  resources :menus, only: [:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      render :new
    end
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :image, :price, :calorie, :protein, :fat, :carbo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/items/index.html.haml
%h1 Items#index
%p Find me in app/views/items/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cvs
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/menus/index.html.haml
%header.header
  %p 商品一覧
  %div.sub 〜気になる商品の詳細を確認しよう！〜
  = link_to "新たな商品を追加する", new_menu_path
.main
  - @menus.each do |menu|
    .main__content
      .main__content--name
        = link_to "#{menu.name}", menu_path(menu.id)
      .main__content--image
        = image_tag "#{menu.image.url}"

app/views/menus/new.html.haml
.container
  %h3 新たな商品を追加する
  = form_with(model: @menu, local: true) do |form|
    .container__celect
      = form.text_field :name, placeholder: "商品名", class: "input-form"
      = form.text_field :price, placeholder: "値段", class: "input-form"
      = form.label :image, class: 'Form-image' do
        = icon('fas', 'camera', class: 'image-icon')
        画像を選択する
        = form.file_field :image, class: "hidden"
      = form.text_field :calorie, placeholder: "カロリー", class: "input-form"
      = form.text_field :protein, placeholder: "タンパク質", class: "input-form"
      = form.text_field :fat, placeholder: "脂質", class: "input-form"
      = form.text_field :carbo, placeholder: "糖質", class: "input-form"
      = form.submit "追加する", class: "input-form add"

app/views/menus/show.html.haml
.product
  .product__detail
    %h1
      = @menu.name
    .product__detail--image
      = image_tag "#{@menu.image}"
    .product__detail--box
      %table
        %tr
          %th 値段（税込み）
          %th カロリー
          %th タンパク質
          %th 脂質
          %th 糖質
        %tr
          %td= @menu.price
          %td= @menu.calorie
          %td= @menu.protein
          %td= @menu.fat
          %td= @menu.carbo
  .product__btn
    = link_to "商品一覧に戻る", menus_path
    = link_to "商品を削除する", menus_path(menu.id), method: :delete